version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    image: bakingoven:latest
    container_name: bakingoven